import "./globals.css";

import { Lato } from "next/font/google";

const lato = Lato({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Next App",
  description: "Generated by Priyanshu Sabaar",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>{children}</body>
    </html>
  );
}
